version: '3.8'
services:
  mongodb:
    image: mongo:4.4.15
    ports:
      - '27017:27017'
    volumes:
      - tradenotedb:/data/db
    env_file: env.env
    restart: always

  tradenote:
    image: barretthugh/tradenote
    ports:
      - '7777:7777'
    depends_on:
      - mongodb
    env_file: env.env
    restart: always

volumes:
  tradenotedb:
    name: tradenotedb
    external: true
